matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
    wordlists:
      - .wordlist.txt
  pipeline:
    - pyspelling.filters.markdown:
    - pyspelling.filters.html:
        comments: false
        attributes:
          - title
          - alt
        ignores:
          - :matches(code, pre)
  sources:
    - '**/*.md'
    - '**/*.markdown'
  expect_match: false
  default_encoding: utf-8
- name: HTML
  aspell:
    lang: en
  sources:
    - '**/*.html'
  default_encoding: utf-8
  dictionary:
    encoding: utf-8
    wordlists:
      - .wordlist.txt
  expect_match: false
  pipeline:
    - pyspelling.filters.html:
        comments: false
        attributes:
          - title
          - alt
        ignores:
          - :matches(code, pre)