matrix:
- name: HTML
  aspell:
    lang: en
  sources:
    - '_site/**/*.html'
  default_encoding: utf-8
  dictionary:
    encoding: utf-8
    wordlists:
      - .wordlist.txt
  expect_match: false
  pipeline:
    - pyspelling.filters.html:
        comments: false
        attributes:
          - title
          - alt
        ignores:
          - :matches(code, pre)