name: Check for broken links

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "./github/**"
      - "README.md"
      - ".gitignore"
  workflow_dispatch:

jobs:
  checklinks:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true
      
      - name: Setup Rubygems, Bundler, jekyll
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true
        run: | 
          gem update --system --no-document
          gem update bundler --no-document
          gem install jekyll bundler
          bundle install
      
      - name: Build jekyll website with drafts
        run: bundle exec jekyll build
      
      - name: Check for broken links
        run: |
          bundle exec htmlproofer --log-level :debug ./_site &> links.log
        continue-on-error: true
      
      - name: Archive log links
        uses: actions/upload-artifact@v1
        if: ${{ failure() }}
        with:
          name: links-check.log
          path: links.log
        