name: Review

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "./github/**"
      - "README.md"
      - ".gitignore"

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true
      
      - name: Setup Rubygems, Bundler, jekyll
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true
        run: | 
          gem update --system --no-document
          gem update bundler --no-document
          gem install jekyll bundler
          bundle install
      
      - name: Build jekyll website with drafts
        run: bundle exec jekyll build
      
      - uses: rojopolis/spellcheck-github-actions@0.20.0
        name: Spellcheck
        with:
          config_path: .spellcheck.yml 