name: Review

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "./github/**"
      - "README.md"
      - ".gitignore"

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: rojopolis/spellcheck-github-actions@0.20.0
        name: Spellcheck
        with:
          config_path: .spellcheck.yml